<?php
 
/**
 * Implementation of hook_entity_info()
 * Registers the menu_fields entity type
 */
 
function menu_fields_entity_info() {
  $options = array(
    'menu_fields' => array(
      'label' => 'Menu Fields',
      'controller class' => 'EntityAPIController',
      'views controller class' => 'EntityDefaultViewsController',
      'base table' => 'menu_fields',
      'fieldable' => TRUE,
      'static cache' => TRUE,
      'entity keys' => array(
        'id' => 'mfid',
      ),
      'bundles' => array(),
      'view modes' => array()
    )
  );

  $options['menu_fields']['bundles']['menu_fields'] = array(
    'label' => 'Default',
    'admin' => array(
      'path' => 'admin/structure/menu/settings',
      'access arguments' => array('administer menu fields'),
    ),
  );

  return $options;
}

/** 
 * Implementation of hook_form_alter()
 * Used to extend the menulink edit form with the custom entity form
 */
function menu_fields_form_menu_edit_item_alter(&$form, &$form_state) {
  //get status
  $mf_enabled = (isset($form['original_item']['#value']['mf_enabled'])) ? $form['original_item']['#value']['mf_enabled'] : 0;
    
  //add enable/disable checkbox
  $form['menu_fields']['mf_enabled'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enabled'),
      '#default_value' => $mf_enabled,
    );

  //add wrapping fieldset  
  $form['menu_fields'] = array(
    '#type' => 'fieldset',
    '#title' => t('Menu Fields'),
    '#tree' => TRUE,
    '#parents' => array('menu_fields'),
  );
  
  //get mfid
  $mfid = (isset($form['original_item']['#value']['mfid'])) ? $form['original_item']['#value']['mfid'] : 0;

  //load entity and attach entity form
  $entity = entity_load('menu_fields', array($mfid));
  field_attach_form('menu_fields', ($mfid) ? $entity[$mfid] : array(), $form['menu_fields'], $form_state);

  //add custom submit function to save entity values
  $form['#submit'][] = 'menu_fields_form_menu_edit_item_submit';
}

/** 
 * Implementation of hook_form_submit()
 */
function menu_fields_form_menu_edit_item_submit(&$form, &$form_state) {

  if(!isset($form_state['complete form']['original_item']['#value']['mfid']) || $form_state['complete form']['original_item']['#value']['mfid'] == 0) {
    //new entity
    $save = (object) array('mfid' => NULL, 'mlid' => $form_state['values']['mlid']);
    drupal_write_record('menu_fields', $save);

    db_update('menu_links')
      ->fields(array('mfid' => $save->mfid))
      ->condition('mlid', $form_state['values']['mlid'])
      ->execute();
      
    field_attach_submit('menu_fields', $save, $form['menu_fields'], $form_state);
    field_attach_insert('menu_fields', $save);
  } else {
    //update old entity fields
    $save = (object) array('mfid' => $form_state['complete form']['original_item']['#value']['mfid'], 'mlid' => $form_state['values']['mlid']);
    
    field_attach_submit('menu_fields', $save, $form['menu_fields'], $form_state);
    field_attach_update('menu_fields', $save);
  }
  
  //update status
  db_update('menu_links')
    ->fields(array('mf_enabled' => $form_state['values']['menu_fields']['mf_enabled']))
    ->condition('mlid', $save->mlid)
    ->execute();
}
 
/**
 * Implementation of hook_menu()
 */
function menu_fields_menu() {
  $items = array();  
  
  //define a new default local task for the menu settings page
  $items['admin/structure/menu/settings/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Implementation of hook_permissions()
 */
function menu_fields_permission() {
  return array(
    'administer menu fields' => array(
      'title' => t('Administer menu fields'),
      'description' => t('Edit the fields and displays for menu fields. '),
    )
  );
}


/**
 * Implementation of hook_views_api()
 * Defines our module as views 3 plugins
 */
function menu_fields_views_api() {
  return array(
    'api' => 3, 
    'path' => drupal_get_path('module', 'menu_fields') . '/views', 
  );
}
